# Simple Reinforcement Learning with Tensorflow: Part 0 - Q-Tables
In this iPython notebook we implement a Q-Table algorithm that solves the FrozenLake problem. To learn more, read here: https://medium.com/@awjuliani/simple-reinforcement-learning-with-tensorflow-part-0-q-learning-with-tables-and-neural-networks-d195264329d0

For more reinforcment learning tutorials, see:
https://github.com/awjuliani/DeepRL-Agents

In [1]:
import gym
import numpy as np
import random
import matplotlib.pyplot as plt
%matplotlib inline

### Load the environment

In [2]:
env = gym.make('FrozenLake-v0')

[2017-03-03 10:26:21,724] Making new env: FrozenLake-v0


### Implement Q-Table learning algorithm

In [3]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .85
y = .99
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

In [5]:
print("Score over time: " +  str(sum(rList)/num_episodes))

Score over time: 0.339


In [6]:
print("Final Q-Table Values")
print(Q)

Final Q-Table Values
[[  1.94787674e-03   2.03525408e-02   3.89988002e-01   1.94535683e-02]
 [  1.81872933e-03   1.64325044e-03   0.00000000e+00   3.92045693e-01]
 [  1.46268144e-02   5.72747702e-03   1.75579966e-02   1.70052178e-01]
 [  6.75933702e-04   6.09285057e-04   3.95684955e-03   1.26070067e-01]
 [  6.25019218e-01   1.49752360e-09   1.07117276e-04   3.51247571e-03]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.16053260e-01   4.97685863e-05   6.92632083e-05   3.55702765e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  5.77829689e-03   1.67129432e-03   2.18628169e-03   8.56163536e-01]
 [  0.00000000e+00   2.65707947e-01   0.00000000e+00   0.00000000e+00]
 [  2.55641666e-02   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  2.59631875e-03   2.25293801e-03   9.62749630e-01   6